<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260829181748 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE persons (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, national_id VARCHAR(20) DEFAULT NULL, id_document VARCHAR(20) DEFAULT NULL, birth_date DATE DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, notes TEXT DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, city_id INT DEFAULT NULL, country_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A25CC7D38BAC62AF ON persons (city_id)');
        $this->addSql('CREATE INDEX IDX_A25CC7D3F92F3E70 ON persons (country_id)');
        $this->addSql('CREATE INDEX idx_persons_name ON persons (last_name, first_name)');
        $this->addSql('CREATE INDEX idx_persons_national_id ON persons (national_id)');
        $this->addSql('ALTER TABLE persons ADD CONSTRAINT FK_A25CC7D38BAC62AF FOREIGN KEY (city_id) REFERENCES cities (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE persons ADD CONSTRAINT FK_A25CC7D3F92F3E70 FOREIGN KEY (country_id) REFERENCES countries (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE persons DROP CONSTRAINT FK_A25CC7D38BAC62AF');
        $this->addSql('ALTER TABLE persons DROP CONSTRAINT FK_A25CC7D3F92F3E70');
        $this->addSql('DROP TABLE persons');
    }
}
