<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260830144645 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Saved face searches: the frame, the ranking and the PDF written into the folder tree';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE face_search_reports (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, searched_by_name VARCHAR(255) NOT NULL, top_score DOUBLE PRECISION DEFAULT NULL, match_threshold DOUBLE PRECISION NOT NULL, report_threshold DOUBLE PRECISION NOT NULL, registry_size INT NOT NULL, candidates JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, searched_by_id INT DEFAULT NULL, query_photo_id INT DEFAULT NULL, matched_person_id INT DEFAULT NULL, pdf_file_id INT DEFAULT NULL, folder_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_30C26C5DEA547A9C ON face_search_reports (searched_by_id)');
        $this->addSql('CREATE INDEX IDX_30C26C5DABB4A759 ON face_search_reports (query_photo_id)');
        $this->addSql('CREATE INDEX IDX_30C26C5DC8608937 ON face_search_reports (matched_person_id)');
        $this->addSql('CREATE INDEX IDX_30C26C5DE071F843 ON face_search_reports (pdf_file_id)');
        $this->addSql('CREATE INDEX IDX_30C26C5D162CB942 ON face_search_reports (folder_id)');
        $this->addSql('CREATE INDEX idx_face_reports_created ON face_search_reports (created_at)');
        $this->addSql('ALTER TABLE face_search_reports ADD CONSTRAINT FK_30C26C5DEA547A9C FOREIGN KEY (searched_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE face_search_reports ADD CONSTRAINT FK_30C26C5DABB4A759 FOREIGN KEY (query_photo_id) REFERENCES files (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE face_search_reports ADD CONSTRAINT FK_30C26C5DC8608937 FOREIGN KEY (matched_person_id) REFERENCES persons (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE face_search_reports ADD CONSTRAINT FK_30C26C5DE071F843 FOREIGN KEY (pdf_file_id) REFERENCES files (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE face_search_reports ADD CONSTRAINT FK_30C26C5D162CB942 FOREIGN KEY (folder_id) REFERENCES folders (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE face_search_reports DROP CONSTRAINT FK_30C26C5DEA547A9C');
        $this->addSql('ALTER TABLE face_search_reports DROP CONSTRAINT FK_30C26C5DABB4A759');
        $this->addSql('ALTER TABLE face_search_reports DROP CONSTRAINT FK_30C26C5DC8608937');
        $this->addSql('ALTER TABLE face_search_reports DROP CONSTRAINT FK_30C26C5DE071F843');
        $this->addSql('ALTER TABLE face_search_reports DROP CONSTRAINT FK_30C26C5D162CB942');
        $this->addSql('DROP TABLE face_search_reports');
    }
}
