<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260829120839 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cities (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, slug VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, county_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D95DB16B85E73F45 ON cities (county_id)');
        $this->addSql('CREATE TABLE companies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, fiscal_code VARCHAR(20) DEFAULT NULL, trade_register_number VARCHAR(30) DEFAULT NULL, person_type VARCHAR(20) NOT NULL, types JSON NOT NULL, address VARCHAR(255) DEFAULT NULL, postal_code VARCHAR(10) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, fax VARCHAR(20) DEFAULT NULL, bank_name VARCHAR(255) DEFAULT NULL, bank_account VARCHAR(34) DEFAULT NULL, credit_limit NUMERIC(12, 2) DEFAULT NULL, payment_term_days INT DEFAULT NULL, status VARCHAR(20) NOT NULL, notes TEXT DEFAULT NULL, contact_person_name VARCHAR(255) DEFAULT NULL, contact_person_phone VARCHAR(20) DEFAULT NULL, contact_person_email VARCHAR(255) DEFAULT NULL, contact_person_position VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, city_id INT DEFAULT NULL, country_id INT DEFAULT NULL, client_type_id INT DEFAULT NULL, industry_id INT DEFAULT NULL, company_size_id INT DEFAULT NULL, account_manager_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8244AA3AD7BBA58B ON companies (fiscal_code)');
        $this->addSql('CREATE INDEX IDX_8244AA3A8BAC62AF ON companies (city_id)');
        $this->addSql('CREATE INDEX IDX_8244AA3AF92F3E70 ON companies (country_id)');
        $this->addSql('CREATE INDEX IDX_8244AA3A9771C8EE ON companies (client_type_id)');
        $this->addSql('CREATE INDEX IDX_8244AA3A2B19A734 ON companies (industry_id)');
        $this->addSql('CREATE INDEX IDX_8244AA3A69DFB2F0 ON companies (company_size_id)');
        $this->addSql('CREATE INDEX IDX_8244AA3A84A5C6C7 ON companies (account_manager_id)');
        $this->addSql('CREATE INDEX idx_companies_name ON companies (name)');
        $this->addSql('CREATE INDEX idx_companies_status ON companies (status)');
        $this->addSql('CREATE INDEX idx_companies_person_type ON companies (person_type)');
        $this->addSql('CREATE TABLE company_contacts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, position VARCHAR(100) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, is_primary BOOLEAN NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, company_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2BD7001E979B1AD6 ON company_contacts (company_id)');
        $this->addSql('CREATE TABLE counties (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, slug VARCHAR(255) NOT NULL, code VARCHAR(10) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, country_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_49886963F92F3E70 ON counties (country_id)');
        $this->addSql('CREATE TABLE countries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(10) DEFAULT NULL, is_active BOOLEAN NOT NULL, is_default BOOLEAN NOT NULL, slug VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE elements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, external_id VARCHAR(255) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, list_id INT NOT NULL, sub_list_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_444A075D3DAE168B ON elements (list_id)');
        $this->addSql('CREATE INDEX IDX_444A075D42764A7F ON elements (sub_list_id)');
        $this->addSql('CREATE TABLE files (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, size INT NOT NULL, type VARCHAR(50) NOT NULL, entity VARCHAR(255) NOT NULL, entity_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, folder_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_files_entity ON files (entity, entity_id)');
        $this->addSql('CREATE INDEX idx_files_type ON files (type)');
        $this->addSql('CREATE INDEX idx_files_folder ON files (folder_id)');
        $this->addSql('CREATE TABLE folders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, type VARCHAR(20) NOT NULL, system_mapping VARCHAR(500) DEFAULT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, parent_id INT DEFAULT NULL, company_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FE37D30FB03A8386 ON folders (created_by_id)');
        $this->addSql('CREATE INDEX idx_folders_parent ON folders (parent_id)');
        $this->addSql('CREATE INDEX idx_folders_type ON folders (type)');
        $this->addSql('CREATE INDEX idx_folders_company ON folders (company_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_folder_parent_slug ON folders (parent_id, slug)');
        $this->addSql('CREATE TABLE lists (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8269FA5989D9B62 ON lists (slug)');
        $this->addSql('CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, title VARCHAR(255) DEFAULT NULL, user_channel VARCHAR(255) NOT NULL, meta JSON DEFAULT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6000B0D3A76ED395 ON notifications (user_id)');
        $this->addSql('CREATE TABLE reset_password_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)');
        $this->addSql('CREATE TABLE settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, setting_key VARCHAR(100) NOT NULL, setting_value VARCHAR(500) DEFAULT NULL, setting_group VARCHAR(50) NOT NULL, setting_type VARCHAR(20) NOT NULL, description VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SETTING_KEY ON settings (setting_key)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, is_verified BOOLEAN DEFAULT false NOT NULL, is_change_password_required BOOLEAN DEFAULT true NOT NULL, phone VARCHAR(20) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uid UUID NOT NULL, company_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9539B0606 ON users (uid)');
        $this->addSql('CREATE INDEX IDX_1483A5E9979B1AD6 ON users (company_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE cities ADD CONSTRAINT FK_D95DB16B85E73F45 FOREIGN KEY (county_id) REFERENCES counties (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE companies ADD CONSTRAINT FK_8244AA3A8BAC62AF FOREIGN KEY (city_id) REFERENCES cities (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE companies ADD CONSTRAINT FK_8244AA3AF92F3E70 FOREIGN KEY (country_id) REFERENCES countries (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE companies ADD CONSTRAINT FK_8244AA3A9771C8EE FOREIGN KEY (client_type_id) REFERENCES elements (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE companies ADD CONSTRAINT FK_8244AA3A2B19A734 FOREIGN KEY (industry_id) REFERENCES elements (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE companies ADD CONSTRAINT FK_8244AA3A69DFB2F0 FOREIGN KEY (company_size_id) REFERENCES elements (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE companies ADD CONSTRAINT FK_8244AA3A84A5C6C7 FOREIGN KEY (account_manager_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE company_contacts ADD CONSTRAINT FK_2BD7001E979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE counties ADD CONSTRAINT FK_49886963F92F3E70 FOREIGN KEY (country_id) REFERENCES countries (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE elements ADD CONSTRAINT FK_444A075D3DAE168B FOREIGN KEY (list_id) REFERENCES lists (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE elements ADD CONSTRAINT FK_444A075D42764A7F FOREIGN KEY (sub_list_id) REFERENCES lists (id)');
        $this->addSql('ALTER TABLE files ADD CONSTRAINT FK_6354059162CB942 FOREIGN KEY (folder_id) REFERENCES folders (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE folders ADD CONSTRAINT FK_FE37D30F727ACA70 FOREIGN KEY (parent_id) REFERENCES folders (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE folders ADD CONSTRAINT FK_FE37D30F979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE folders ADD CONSTRAINT FK_FE37D30FB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cities DROP CONSTRAINT FK_D95DB16B85E73F45');
        $this->addSql('ALTER TABLE companies DROP CONSTRAINT FK_8244AA3A8BAC62AF');
        $this->addSql('ALTER TABLE companies DROP CONSTRAINT FK_8244AA3AF92F3E70');
        $this->addSql('ALTER TABLE companies DROP CONSTRAINT FK_8244AA3A9771C8EE');
        $this->addSql('ALTER TABLE companies DROP CONSTRAINT FK_8244AA3A2B19A734');
        $this->addSql('ALTER TABLE companies DROP CONSTRAINT FK_8244AA3A69DFB2F0');
        $this->addSql('ALTER TABLE companies DROP CONSTRAINT FK_8244AA3A84A5C6C7');
        $this->addSql('ALTER TABLE company_contacts DROP CONSTRAINT FK_2BD7001E979B1AD6');
        $this->addSql('ALTER TABLE counties DROP CONSTRAINT FK_49886963F92F3E70');
        $this->addSql('ALTER TABLE elements DROP CONSTRAINT FK_444A075D3DAE168B');
        $this->addSql('ALTER TABLE elements DROP CONSTRAINT FK_444A075D42764A7F');
        $this->addSql('ALTER TABLE files DROP CONSTRAINT FK_6354059162CB942');
        $this->addSql('ALTER TABLE folders DROP CONSTRAINT FK_FE37D30F727ACA70');
        $this->addSql('ALTER TABLE folders DROP CONSTRAINT FK_FE37D30F979B1AD6');
        $this->addSql('ALTER TABLE folders DROP CONSTRAINT FK_FE37D30FB03A8386');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3A76ED395');
        $this->addSql('ALTER TABLE reset_password_request DROP CONSTRAINT FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E9979B1AD6');
        $this->addSql('DROP TABLE cities');
        $this->addSql('DROP TABLE companies');
        $this->addSql('DROP TABLE company_contacts');
        $this->addSql('DROP TABLE counties');
        $this->addSql('DROP TABLE countries');
        $this->addSql('DROP TABLE elements');
        $this->addSql('DROP TABLE files');
        $this->addSql('DROP TABLE folders');
        $this->addSql('DROP TABLE lists');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE settings');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
