<?php

declare(strict_types=1);

namespace DoctrineMigrations\Audit;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260829120854 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE access_logs (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, username VARCHAR(255) DEFAULT NULL, user_roles JSON DEFAULT NULL, route_name VARCHAR(255) DEFAULT NULL, url TEXT DEFAULT NULL, method VARCHAR(10) DEFAULT NULL, controller VARCHAR(255) DEFAULT NULL, action VARCHAR(100) DEFAULT NULL, request_params JSON DEFAULT NULL, response_code SMALLINT DEFAULT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent TEXT DEFAULT NULL, session_id VARCHAR(128) DEFAULT NULL, referer VARCHAR(500) DEFAULT NULL, execution_time DOUBLE PRECISION DEFAULT NULL, memory_usage INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_access_user_id ON access_logs (user_id)');
        $this->addSql('CREATE INDEX idx_access_route_name ON access_logs (route_name)');
        $this->addSql('CREATE INDEX idx_access_created_at ON access_logs (created_at)');
        $this->addSql('CREATE INDEX idx_access_user_created ON access_logs (user_id, created_at)');
        $this->addSql('CREATE INDEX idx_access_response_code ON access_logs (response_code)');
        $this->addSql('CREATE TABLE authentication_logs (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT DEFAULT NULL, username VARCHAR(255) DEFAULT NULL, event_type VARCHAR(50) NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent TEXT DEFAULT NULL, success BOOLEAN NOT NULL, failure_reason VARCHAR(255) DEFAULT NULL, session_id VARCHAR(128) DEFAULT NULL, additional_data JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_auth_user_id ON authentication_logs (user_id)');
        $this->addSql('CREATE INDEX idx_auth_event_type ON authentication_logs (event_type)');
        $this->addSql('CREATE INDEX idx_auth_created_at ON authentication_logs (created_at)');
        $this->addSql('CREATE INDEX idx_auth_success ON authentication_logs (success)');
        $this->addSql('CREATE INDEX idx_auth_ip_address ON authentication_logs (ip_address)');
        $this->addSql('CREATE TABLE entity_change_logs (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entity_class VARCHAR(100) NOT NULL, entity_id INT NOT NULL, action VARCHAR(10) NOT NULL, changes JSON DEFAULT NULL, user_id INT DEFAULT NULL, username VARCHAR(255) DEFAULT NULL, entity_label VARCHAR(255) DEFAULT NULL, ip_address VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_change_entity ON entity_change_logs (entity_class, entity_id)');
        $this->addSql('CREATE INDEX idx_change_user_id ON entity_change_logs (user_id)');
        $this->addSql('CREATE INDEX idx_change_created_at ON entity_change_logs (created_at)');
        $this->addSql('CREATE INDEX idx_change_action ON entity_change_logs (action)');
        $this->addSql('CREATE INDEX idx_change_entity_date ON entity_change_logs (entity_class, created_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE access_logs');
        $this->addSql('DROP TABLE authentication_logs');
        $this->addSql('DROP TABLE entity_change_logs');
    }
}
